import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// IMPORTING COMPONENTS
import ProgressBar from "@/components/ProgressBar"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="bg-[#050012] min-h-screen transition-all duration-500 ease-in-out">
          <ProgressBar />
          {children}
        </main>
      </body>
    </html>
  );
}
